// Generated by CoffeeScript 1.6.3
(function() {
  var Application, Helpers, Q, Uglify, merge, path;

  path = require('path');

  Uglify = require('uglify-js');

  Q = require('q');

  merge = require('recursive-merge');

  Helpers = require('../Helpers');

  Application = (function() {
    Application.prototype.minify = false;

    Application.prototype.loader = null;

    Application.prototype.pckg = null;

    Application.prototype.basePath = null;

    Application.prototype.section = null;

    Application.prototype.v = false;

    function Application(loader, pckg, basePath, section) {
      this.loader = loader;
      this.pckg = pckg;
      this.basePath = basePath;
      this.section = section;
    }

    Application.prototype.parseLibraries = function(type) {
      return this.loader.loadFiles(this.section.libraries[type]);
    };

    Application.prototype.parseAliases = function() {
      var alias, m, result, _ref;
      result = [];
      _ref = this.section.aliases;
      for (alias in _ref) {
        m = _ref[alias];
        result.push("'" + alias + "': '" + m + "'");
      }
      return result;
    };

    Application.prototype.loadBaseModuleFile = function() {
      var deferred;
      deferred = Q.defer();
      this.loader.loadFile(path.resolve(__dirname + '/../Module.js')).then(function(content) {
        content = content.replace(/\s+$/, '').replace(/;$/, '');
        return deferred.resolve(content);
      }, function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Application.prototype.loadModules = function() {
      var deferred,
        _this = this;
      deferred = Q.defer();
      this.pckg.findDependenciesForModules(this.section.modules).then(function(data) {
        return _this.loader.loadModules(data.files, _this.section.base).then(function(modules) {
          var result;
          modules = modules.concat(_this.parseAliases());
          result = {
            modules: modules.join(',\n'),
            node: _this.pckg.parseNodeInfo(data.node, _this.basePath)
          };
          return deferred.resolve(result);
        }, function(err) {
          return deferred.reject(err);
        });
      }, function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Application.prototype.loadFsModules = function() {
      var deferred, modules, paths, _path, _ref;
      deferred = Q.defer();
      modules = [];
      _ref = this.section.fsModules;
      for (_path in _ref) {
        paths = _ref[_path];
        modules.push(this.loadFsModule(_path, paths));
      }
      Q.all(modules).then(function(data) {
        return deferred.resolve(data);
      }, function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Application.prototype.loadFsModule = function(_path, paths) {
      var deferred, info,
        _this = this;
      deferred = Q.defer();
      info = this.pckg.loadModuleInfo("" + _path + "/package.json");
      this.pckg.findDependenciesForModules(paths).then(function(deps) {
        var file, modules, _i, _len, _name, _ref;
        modules = {};
        _ref = deps.files;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          file = _ref[_i];
          _name = info.name + '/' + path.relative(_path, file);
          modules[_name] = file;
        }
        return _this.loader.loadModules(modules, _path).then(function(result) {
          result = {
            modules: result.join(',\n'),
            node: _this.pckg.parseNodeInfo(deps.node, path.dirname(_path))
          };
          return deferred.resolve(result);
        }, function(err) {
          return deferred.reject(err);
        });
      }, function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Application.prototype.loadCoreModules = function() {
      var deferred, m, msg, name, paths, promises, _i, _len, _path, _ref;
      deferred = Q.defer();
      promises = [];
      msg = [];
      _ref = this.section.coreModules;
      for (name in _ref) {
        _path = _ref[name];
        msg.push("Loading core module '" + name + "' from '" + _path + "'");
        promises.push(this.loader.loadModule(_path, null, name));
      }
      if (promises.length === 0) {
        return Q.resolve('');
      }
      if (this.v) {
        paths = this.pckg.getSystemModulesPath();
        if (paths.length === 0) {
          console.log('Core modules will not be loaded. No system module path found.');
        } else {
          console.log('Core modules will be searched in these paths:\n' + paths.join('\n'));
        }
        for (_i = 0, _len = msg.length; _i < _len; _i++) {
          m = msg[_i];
          console.log(m);
        }
      }
      Q.all(promises).then(function(data) {
        data = data.join(',\n');
        return deferred.resolve(data);
      });
      return deferred.promise;
    };

    Application.prototype.parseModules = function() {
      var deferred,
        _this = this;
      deferred = Q.defer();
      Q.all([this.loadModules(), this.loadBaseModuleFile(), this.loadFsModules(), this.loadCoreModules()]).then(function(data) {
        var final, pack, result, _i, _len, _ref;
        final = {
          modules: data[0].modules,
          node: data[0].node
        };
        _ref = data[2];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pack = _ref[_i];
          if (final.modules !== '' && pack.modules !== '') {
            final.modules += ',\n';
          }
          if (pack.modules !== '') {
            final.modules += pack.modules;
          }
          final.node = merge(final.node, pack.node);
        }
        if (data[3] !== '') {
          if (final.modules !== '') {
            final.modules += ',\n';
          }
          final.modules += data[3];
        }
        final.node = JSON.stringify(final.node);
        result = {
          modules: "" + data[1] + "({\n" + final.modules + "\n});",
          node: "require._setMeta(" + final.node + ");\n"
        };
        return deferred.resolve(result);
      }, function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Application.prototype.parseRun = function() {
      var m, match, run, _i, _len, _ref;
      run = [];
      _ref = this.section.run;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        m = _ref[_i];
        if ((match = m.match(/^<(.+)>$/)) === null) {
          run.push("require('" + m + "');");
        } else {
          run.push(match[1]);
        }
      }
      return Q.resolve(run);
    };

    Application.prototype.parse = function() {
      var deferred,
        _this = this;
      deferred = Q.defer();
      Q.all([this.parseLibraries('begin'), this.parseModules(), this.parseRun(), this.parseLibraries('end')]).then(function(data) {
        var result;
        result = [].concat(data[0], data[1].modules, data[1].node, data[2], data[3]);
        result = result.join('\n\n');
        if (_this.minify === true) {
          result = Uglify.minify(result, {
            fromString: true
          }).code;
        }
        return deferred.resolve(result);
      }, function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    return Application;

  })();

  module.exports = Application;

}).call(this);
