// Generated by CoffeeScript 1.6.3
(function() {
  var Application, Compiler, Loader, Parser, Q, Style;

  Q = require('q');

  Application = require('./Application');

  Style = require('./Style');

  Loader = require('../Loader');

  Compiler = require('source-compiler');

  Parser = (function() {
    Parser.prototype.simq = null;

    Parser.prototype.config = null;

    Parser.prototype.loader = null;

    Parser.prototype.basePath = null;

    function Parser(simq, basePath) {
      this.simq = simq;
      this.basePath = basePath;
      this.config = this.simq.config.load();
      this.loader = new Loader;
      this.loader.jquerify = this.config.template.jquerify;
      if (this.config.cache.directory !== null) {
        Compiler.setCache(this.config.cache.directory);
      }
    }

    Parser.prototype.parseApplication = function(section, name) {
      return (new Application(this.simq, this.loader, this.basePath, section, name)).parse();
    };

    Parser.prototype.parseStyle = function(path, name) {
      return (new Style(this.loader)).parse(path, this.config.packages[name]);
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
