// Generated by CoffeeScript 1.6.3
(function() {
  var Application, Compiler, Loader, Parser, Q, Style;

  Q = require('q');

  Application = require('./Application');

  Style = require('./Style');

  Loader = require('../Loader');

  Compiler = require('source-compiler');

  Parser = (function() {
    Parser.prototype.simq = null;

    Parser.prototype.config = null;

    Parser.prototype.loader = null;

    Parser.prototype.basePath = null;

    function Parser(simq, basePath) {
      this.simq = simq;
      this.basePath = basePath;
      this.config = this.simq.config.load();
      this.loader = new Loader;
      this.loader.jquerify = this.config.template.jquerify;
      if (this.config.cache.directory !== null) {
        Compiler.setCache(this.config.cache.directory);
      }
    }

    Parser.prototype.parseApplication = function(section) {
      var application, basePath;
      basePath = section.base === null ? this.basePath : this.basePath + '/' + section.base;
      application = new Application(this.loader, basePath, section);
      application.minify = !this.config["debugger"].scripts;
      return application.parse();
    };

    Parser.prototype.parseStyle = function(section) {
      var basePath;
      basePath = section.base === null ? this.basePath : this.basePath + '/' + section.base;
      return (new Style(this.loader, basePath, section)).parse();
    };

    return Parser;

  })();

  module.exports = Parser;

}).call(this);
