// Generated by CoffeeScript 1.6.3
(function() {
  var Style, path;

  path = require('path');

  Style = (function() {
    Style.prototype.loader = null;

    Style.prototype.basePath = null;

    Style.prototype.section = null;

    function Style(loader, basePath, section) {
      this.loader = loader;
      this.basePath = basePath;
      this.section = section;
    }

    Style.prototype.parse = function() {
      var dep, dependents, _i, _len, _path, _ref;
      dependents = null;
      if (this.section.style.dependencies !== null) {
        dependents = [];
        _ref = this.section.style.dependencies;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          dep = _ref[_i];
          dependents.push(path.resolve(this.basePath + '/' + dep));
        }
      }
      _path = path.resolve(this.basePath + '/' + this.section.style["in"]);
      return this.loader.loadFile(_path, dependents);
    };

    return Style;

  })();

  module.exports = Style;

}).call(this);
