// Generated by CoffeeScript 1.6.3
(function() {
  var Style, fs, less, _path;

  _path = require('path');

  less = require('less');

  fs = require('fs');

  Style = (function() {
    Style.prototype.simq = null;

    Style.prototype.loader = null;

    Style.prototype.basePath = null;

    function Style(simq, loader, basePath) {
      this.simq = simq;
      this.loader = loader;
      this.basePath = basePath;
    }

    Style.prototype.parse = function(path, minify, fn) {
      var file, options;
      if (minify == null) {
        minify = true;
      }
      path = _path.resolve(path);
      file = fs.readFileSync(path).toString();
      options = {
        paths: [_path.dirname(path)],
        optimization: 1,
        filename: path,
        rootpath: '',
        relativeUrls: false,
        strictImports: false,
        compress: minify
      };
      less.render(file, options, function(e, content) {
        return fn(content);
      });
      return this;
    };

    return Style;

  })();

  module.exports = Style;

}).call(this);
