// Generated by CoffeeScript 1.6.3
(function() {
  var Commands, Finder, SimQ, commands, dir, expect, path, rimraf, simq;

  expect = require('chai').expect;

  path = require('path');

  Finder = require('fs-finder');

  rimraf = require('rimraf');

  SimQ = require('../../lib/_SimQ');

  Commands = require('../../lib/Commands');

  dir = path.resolve(__dirname + '/../data');

  simq = null;

  commands = null;

  describe('Commands', function() {
    beforeEach(function() {
      simq = new SimQ(dir);
      return commands = new Commands(simq);
    });
    return describe('#create()', function() {
      it('should throw an error if path already exists', function(done) {
        return commands.create('package').fail(function(err) {
          expect(err).to.be.an["instanceof"](Error);
          expect(err.message).to.be.equal('Directory package already exists.');
          return done();
        }).done();
      });
      return it('should create new project from sandbox', function(done) {
        return commands.create('test').then(function() {
          var files;
          files = Finder.findFiles(dir + '/test/*');
          expect(files).to.be.eql([dir + '/test/config/setup.json', dir + '/test/css/style.less', dir + '/test/public/application.js', dir + '/test/public/index.html']);
          return rimraf(dir + '/test', function() {
            return done();
          });
        }).done();
      });
    });
  });

}).call(this);
