// Generated by CoffeeScript 1.6.3
(function() {
  var Commands, Configurator, Factory, Finder, SimQ, commands, dir, expect, path, rimraf, simq;

  expect = require('chai').expect;

  path = require('path');

  Finder = require('fs-finder');

  rimraf = require('rimraf');

  SimQ = require('../../lib/_SimQ');

  Commands = require('../../lib/Commands');

  Factory = require('../../lib/Package/Factory');

  Configurator = require('../../lib/_Config/Configurator');

  dir = path.resolve(__dirname + '/../data');

  simq = null;

  commands = null;

  describe('Commands', function() {
    beforeEach(function() {
      simq = new SimQ(dir);
      return commands = new Commands(simq);
    });
    describe('#create()', function() {
      it('should throw an error if path already exists', function(done) {
        return commands.create('package').fail(function(err) {
          expect(err).to.be.an["instanceof"](Error);
          expect(err.message).to.be.equal('Directory package already exists.');
          return done();
        }).done();
      });
      it('should create new project from sandbox', function(done) {
        return commands.create('test').then(function() {
          var files;
          files = Finder.findFiles(dir + '/test/*');
          expect(files).to.be.eql([dir + '/test/config/setup.json', dir + '/test/css/style.less', dir + '/test/package.json', dir + '/test/public/application.js', dir + '/test/public/index.html']);
          return rimraf(dir + '/test', function() {
            return done();
          });
        }).done();
      });
      return it('should build application from sandbox', function(done) {
        return commands.create('test').then(function() {
          var c, configurator, pckg, s;
          s = new SimQ(dir + '/test');
          c = new Commands(s);
          configurator = new Configurator(dir + '/test/config/setup.json');
          pckg = Factory.create(s.basePath, configurator.load().packages.application);
          s.addPackage('test', pckg);
          return c.build().then(function() {
            return rimraf(dir + '/test', function() {
              return done();
            });
          }).done();
        }).done();
      });
    });
    return describe.skip('#clean()', function() {
      return it('should remove all files created by simq', function(done) {
        return commands.create('test').then(function() {
          var configurator, pckg;
          simq = new SimQ(dir + '/test');
          commands = new Commands(simq);
          configurator = new Configurator(dir + '/test/config/setup.json');
          pckg = Factory.create(simq.basePath, configurator.load().packages.application);
          simq.addPackage('test', pckg);
          return commands.build().then(function() {
            return rimraf(dir + '/test', function() {
              return done();
            });
          }).done();
        }).done();
      });
    });
  });

}).call(this);
