// Generated by CoffeeScript 1.6.3
(function() {
  var CacheExtension, Extension, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Extension = require('easy-configuration/lib/Extension');

  CacheExtension = (function(_super) {
    __extends(CacheExtension, _super);

    function CacheExtension() {
      _ref = CacheExtension.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CacheExtension.prototype.defaults = {
      directory: null
    };

    CacheExtension.prototype.loadConfiguration = function() {
      return this.getConfig(this.defaults);
    };

    return CacheExtension;

  })(Extension);

  module.exports = CacheExtension;

}).call(this);
