// Generated by CoffeeScript 1.6.3
(function() {
  var DebuggerExtension, Extension, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Extension = require('easy-configuration/lib/Extension');

  DebuggerExtension = (function(_super) {
    __extends(DebuggerExtension, _super);

    function DebuggerExtension() {
      _ref = DebuggerExtension.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    DebuggerExtension.prototype.defaults = {
      styles: false,
      scripts: false,
      sourceMap: false,
      sourceMaps: false
    };

    DebuggerExtension.prototype.loadConfiguration = function() {
      var config;
      config = this.getConfig(this.defaults);
      if (config.sourceMap === true && config.sourceMaps === false) {
        config.sourceMaps = config.sourceMap;
      }
      delete config.sourceMap;
      return config;
    };

    return DebuggerExtension;

  })(Extension);

  module.exports = DebuggerExtension;

}).call(this);
