// Generated by CoffeeScript 1.6.2
(function() {
  var Config, fs;

  fs = require('fs');

  Config = (function() {
    Config.prototype.path = '';

    Config.prototype.data = null;

    function Config(path) {
      this.path = path;
    }

    Config.prototype.load = function() {
      var config;

      if (this.data === null) {
        if (!fs.existsSync(this.path)) {
          throw new Error('Config file ' + this.path + ' was not found.');
        }
        this.data = JSON.parse(fs.readFileSync(this.path));
        if (this.data.main) {
          this.data.application = this.data.main;
          delete this.data.main;
        }
        if (!this.data.packages) {
          config = {
            packages: {
              __main__: this.data
            }
          };
          this.data = config;
        }
      }
      return this.data;
    };

    return Config;

  })();

  module.exports = Config;

}).call(this);
