// Generated by CoffeeScript 1.6.3
(function() {
  var Finder, Helpers, Module, fs, path;

  Finder = require('fs-finder');

  Module = require('module');

  fs = require('fs');

  path = require('path');

  Helpers = (function() {
    function Helpers() {}

    Helpers.getGlobalsForModule = function(name) {
      var dir, globals, key, result, value;
      dir = path.dirname(name);
      globals = {
        require: "function(name) {return window.require(name, '" + name + "');}",
        '-- require.resolve': "function(name, parent) {if (parent === null) {parent = '" + name + "';} return window.require.resolve(name, parent);}",
        '-- require.define': "function(bundle) {window.require.define(bundle);}",
        '-- require.cache': "window.require.cache",
        __filename: "'" + name + "'",
        __dirname: "'" + dir + "'",
        process: "{cwd: function() {return '/';}, argv: ['node', '" + name + "'], env: {}}"
      };
      result = [];
      for (key in globals) {
        value = globals[key];
        key = key.match(/^--\s/) === null ? "var " + key : key.replace(/^--\s/, '');
        result.push("" + key + " = " + value + ";");
      }
      return result;
    };

    Helpers.getCoreModulesPaths = function() {
      return Module.globalPaths;
    };

    Helpers.getCoreModulePath = function(name) {
      var dir, _i, _len, _path, _ref;
      _ref = this.getCoreModulesPaths();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        dir = _ref[_i];
        _path = "" + dir + "/" + name + ".js";
        if (fs.existsSync(_path) && fs.statSync(_path).isFile()) {
          return _path;
        }
      }
      return null;
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
