// Generated by CoffeeScript 1.6.3
(function() {
  var Finder, Helpers, fs, path;

  Finder = require('fs-finder');

  fs = require('fs');

  path = require('path');

  Helpers = (function() {
    function Helpers() {}

    Helpers.expandFilesList = function(paths, basePath) {
      var result, _i, _len, _path;
      if (basePath == null) {
        basePath = null;
      }
      result = [];
      for (_i = 0, _len = paths.length; _i < _len; _i++) {
        _path = paths[_i];
        if (_path.match(/^http/) === null) {
          if (basePath !== null) {
            _path = basePath + '/' + _path;
          }
          _path = path.resolve(_path);
          if (fs.existsSync(_path) && fs.statSync(_path).isFile()) {
            result.push(_path);
          } else {
            result = result.concat(Finder.findFiles(_path));
          }
        } else {
          result.push(_path);
        }
      }
      return this.removeDuplicates(result);
    };

    Helpers.removeDuplicates = function(array) {
      return array.filter(function(el, pos) {
        return array.indexOf(el) === pos;
      });
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
