// Generated by CoffeeScript 1.6.2
(function() {
  var Loader, coffee, eco, fs, _path;

  _path = require('path');

  fs = require('fs');

  coffee = require('coffee-script');

  eco = require('eco');

  Loader = (function() {
    Loader.prototype.simq = null;

    function Loader(simq) {
      this.simq = simq;
    }

    Loader.prototype.loadFile = function(path) {
      var ext, file;

      path = _path.resolve(path);
      ext = _path.extname(path).substring(1).toLowerCase();
      if (typeof this.loaders[ext] === 'undefined') {
        throw new Error('File .' + ext + ' is not supported');
      }
      file = fs.readFileSync(path, 'utf8').toString();
      file = this.loaders[ext](file);
      file = this.normalize(file);
      return file;
    };

    Loader.prototype.loadModule = function(path) {
      var ext, lib, name;

      path = _path.normalize(path);
      ext = _path.extname(path).substring(1).toLowerCase();
      if (typeof this.compilers[ext] === 'undefined') {
        throw new Error('Module of type ' + ext + ' is not supported');
      }
      lib = this.loadFile(path).replace(/\n/g, '\n\t\t');
      name = this.simq.getModuleName(path);
      lib = this.compilers[ext](lib);
      return '\'' + name + '\': function(exports, require, module) {\n\t\t' + lib + '\n\t}';
    };

    Loader.prototype.loadModules = function(dir, type) {
      var files, name, result, stats, _i, _len;

      if (type == null) {
        type = null;
      }
      dir = _path.normalize(dir);
      files = fs.readdirSync(dir);
      result = new Array;
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        name = files[_i];
        name = dir + name;
        stats = fs.statSync(name);
        if (stats.isFile() && name.substring(name.length - 1) !== '~') {
          if (type) {
            if (_path.extname(name).toLowerCase() !== '.' + type) {
              continue;
            }
          }
          result.push(this.loadModule(name));
        } else if (stats.isDirectory()) {
          result = result.concat(this.loadModules(name + '/', type));
        }
      }
      return result;
    };

    Loader.prototype.normalize = function(content) {
      content = content.replace(/^\s+|\s+$/g, '');
      return content;
    };

    Loader.prototype.loaders = {
      js: function(content) {
        return content;
      },
      coffee: function(content) {
        return coffee.compile(content);
      },
      json: function(content) {
        return content;
      },
      eco: function(content) {
        return eco.precompile(content);
      }
    };

    Loader.prototype.compilers = {
      js: function(content) {
        return 'return ' + content;
      },
      coffee: function(content) {
        return 'return ' + content;
      },
      json: function(content) {
        return 'module.exports = ' + content;
      },
      eco: function(content) {
        return 'module.exports = ' + content;
      }
    };

    return Loader;

  })();

  module.exports = Loader;

}).call(this);
