// Generated by CoffeeScript 1.6.3
(function() {
  var Logger, fs, path;

  path = require('path');

  fs = require('fs');

  Logger = (function() {
    Logger.prototype.path = null;

    Logger.prototype.logged = false;

    Logger.prototype.running = true;

    function Logger(_path) {
      this.path = _path === 'console' ? _path : path.resolve(_path);
    }

    Logger.prototype.log = function(message) {
      if (this.running) {
        if (this.logged === false) {
          this.logged = true;
          if (this.path !== 'console') {
            this.log('======================== ' + (new Date).toLocaleString() + ' ========================');
          }
        }
        if (this.path === 'console') {
          console.log(message);
        } else {
          fs.appendFileSync(this.path, message + '\n');
        }
      }
      return message;
    };

    return Logger;

  })();

  module.exports = Logger;

}).call(this);
