// Generated by CoffeeScript 1.6.2
(function() {
  var Module;

  Module = (function() {
    Module.prototype.modules = null;

    Module.prototype.cache = null;

    function Module() {
      this.modules = {};
      this.cache = {};
    }

    Module.prototype.register = function(path, lib) {
      this.modules[path] = lib;
      return this;
    };

    Module.prototype.addAlias = function(alias, module) {
      if (typeof this.modules[module] === 'undefined') {
        throw new Error('Module ' + module + ' was not found.');
      }
      this.modules[alias] = module;
      return this;
    };

    Module.prototype.require = function(path) {
      var module;

      if (typeof this.modules[path] === 'undefined') {
        throw new Error('Module ' + path + ' was not found.');
      }
      if (typeof this.modules[path] === 'string') {
        path = this.modules[path];
      }
      if (typeof this.cache[path] === 'undefined') {
        module = {
          exports: {}
        };
        this.modules[path].apply(window, [module]);
        this.cache[path] = module;
      }
      return this.cache[path].exports;
    };

    return Module;

  })();

  window._module = new Module;

  window.require = function(path) {
    return window._module.require(path);
  };

}).call(this);
