// Generated by CoffeeScript 1.6.3
(function() {
  var Configurator, Factory, Package, configDir, dir, expect, getConfig, path;

  expect = require('chai').expect;

  path = require('path');

  Factory = require('../../../lib/Package/Factory');

  Package = require('../../../lib/Package/Package');

  Configurator = require('../../../lib/_Config/Configurator');

  dir = path.resolve(__dirname + '/../../data/package');

  configDir = dir + '/config';

  getConfig = function(name) {
    return (new Configurator(configDir + '/' + name + '.json')).load();
  };

  describe('Package/Factory', function() {
    return describe('#create()', function() {
      return it('shoult create empty package', function() {
        var config, pckg;
        config = getConfig('empty');
        pckg = Factory.create(dir, config.packages.application);
        expect(pckg).to.be.an["instanceof"](Package);
        expect(pckg.basePath).to.be.equal(dir);
        expect(pckg.skip).to.be["false"];
        expect(pckg.base).to.be["null"];
        expect(pckg.application).to.be["null"];
        expect(pckg.style).to.be["null"];
        expect(pckg.modules).to.be.eql([]);
        return expect(pckg.run).to.be.eql([]);
      });
    });
  });

}).call(this);
