// Generated by CoffeeScript 1.6.3
(function() {
  var Configurator, Factory, dir, expect, getConfig, path;

  expect = require('chai').expect;

  path = require('path');

  Factory = require('../../../lib/Package/Factory');

  Configurator = require('../../../lib/_Config/Configurator');

  dir = path.resolve(__dirname + '/../../data/package/config');

  getConfig = function(name) {
    return (new Configurator(dir + '/' + name + '.json')).load();
  };

  describe('Package/Factory', function() {
    return describe('#create()', function() {
      return it('shoult create empty package', function() {
        var config, pckg;
        config = getConfig('empty');
        return pckg = Factory.create(config.packages.application);
      });
    });
  });

}).call(this);
