// Generated by CoffeeScript 1.6.3
(function() {
  var Configurator, EasyConfigurator, PackageExtension, TemplateExtension,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EasyConfigurator = require('easy-configuration');

  PackageExtension = require('./PackageExtension');

  TemplateExtension = require('./TemplateExtension');

  Configurator = (function(_super) {
    __extends(Configurator, _super);

    function Configurator(fileName) {
      Configurator.__super__.constructor.call(this, fileName);
      this.addExtension('packages', new PackageExtension);
      this.addExtension('template', new TemplateExtension);
    }

    return Configurator;

  })(EasyConfigurator);

  module.exports = Configurator;

}).call(this);
