// Generated by CoffeeScript 1.6.3
(function() {
  var CacheExtension, Configurator, DebuggerExtension, EasyConfigurator, PackageExtension, RoutesExtension, ServerExtension, TemplateExtension,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EasyConfigurator = require('easy-configuration');

  PackageExtension = require('./PackageExtension');

  TemplateExtension = require('./TemplateExtension');

  CacheExtension = require('./CacheExtension');

  DebuggerExtension = require('./DebuggerExtension');

  ServerExtension = require('./ServerExtension');

  RoutesExtension = require('./RoutesExtension');

  Configurator = (function(_super) {
    __extends(Configurator, _super);

    function Configurator(fileName, basePath) {
      Configurator.__super__.constructor.call(this, fileName);
      this.addExtension('packages', new PackageExtension(basePath));
      this.addExtension('template', new TemplateExtension);
      this.addExtension('cache', new CacheExtension);
      this.addExtension('debugger', new DebuggerExtension);
      this.addExtension('server', new ServerExtension);
      this.addExtension('routes', new RoutesExtension);
    }

    return Configurator;

  })(EasyConfigurator);

  module.exports = Configurator;

}).call(this);
