// Generated by CoffeeScript 1.6.3
(function() {
  var DebuggerExtension, Extension,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Extension = require('easy-configuration/lib/Extension');

  DebuggerExtension = (function(_super) {
    __extends(DebuggerExtension, _super);

    DebuggerExtension.prototype.defaults = {
      styles: null,
      scripts: null,
      sourceMap: false
    };

    DebuggerExtension.prototype.debug = false;

    function DebuggerExtension(debug) {
      this.debug = debug;
    }

    DebuggerExtension.prototype.loadConfiguration = function() {
      var config;
      config = this.getConfig(this.defaults);
      if (config.styles === null) {
        config.styles = this.debug;
      }
      if (config.scripts === null) {
        config.scripts = this.debug;
      }
      return config;
    };

    return DebuggerExtension;

  })(Extension);

  module.exports = DebuggerExtension;

}).call(this);
