// Generated by CoffeeScript 1.6.3
(function() {
  var Extension, RoutesExtension, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Extension = require('easy-configuration/lib/Extension');

  RoutesExtension = (function(_super) {
    __extends(RoutesExtension, _super);

    function RoutesExtension() {
      _ref = RoutesExtension.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RoutesExtension.prototype.defaults = {
      prefix: null,
      main: './public/index.html',
      routes: {}
    };

    RoutesExtension.prototype.loadConfiguration = function() {
      return this.getConfig(this.defaults);
    };

    return RoutesExtension;

  })(Extension);

  module.exports = RoutesExtension;

}).call(this);
