// Generated by CoffeeScript 1.6.3
(function() {
  var Extension, TemplateExtension, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Extension = require('easy-configuration/lib/Extension');

  TemplateExtension = (function(_super) {
    __extends(TemplateExtension, _super);

    function TemplateExtension() {
      _ref = TemplateExtension.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TemplateExtension.prototype.defaults = {
      jquerify: false
    };

    TemplateExtension.prototype.loadConfiguration = function() {
      return this.getConfig(this.defaults);
    };

    return TemplateExtension;

  })(Extension);

  module.exports = TemplateExtension;

}).call(this);
