// Generated by CoffeeScript 1.6.3
(function() {
  var Builder, Info, Package, builder, dir, expect, path, pckg;

  expect = require('chai').expect;

  path = require('path');

  Info = require('module-info');

  Package = require('../../../lib/Package/Package');

  Builder = require('../../../lib/Package/Builder');

  dir = path.resolve(__dirname + '/../../data/package');

  pckg = null;

  builder = null;

  describe('Package/Builder', function() {
    beforeEach(function() {
      pckg = new Package(dir);
      return builder = new Builder(pckg);
    });
    return describe('#buildModules()', function() {
      return it('should build one module from absolute path', function(done) {
        pckg.addModule(dir + '/modules/1.js');
        return builder.buildModules().then(function(data) {
          return done();
        }).done();
      });
    });
  });

}).call(this);
