// Generated by CoffeeScript 1.6.3
(function() {
  var Info, Package, dir, expect, path, pckg;

  expect = require('chai').expect;

  path = require('path');

  Info = require('module-info');

  Package = require('../../../lib/Package/Package');

  dir = path.resolve(__dirname + '/../../data/package');

  pckg = null;

  describe('_Package', function() {
    beforeEach(function() {
      return pckg = new Package(dir);
    });
    describe('#setApplication()', function() {
      return it('should set path for result js file', function() {
        pckg.setApplication('./public/application.js');
        return expect(pckg.application).to.be.equal(dir + '/public/application.js');
      });
    });
    describe('#setStyle()', function() {
      it('should set paths for styles without dependent files', function() {
        pckg.setStyle('./css/style.less', './public/style.css');
        expect(pckg.style["in"]).to.be.equal(dir + '/css/style.less');
        expect(pckg.style.out).to.be.equal(dir + '/public/style.css');
        return expect(pckg.style.dependencies).to.be["null"];
      });
      return it('should set paths for styles with dependent files', function() {
        pckg.setStyle('./css/style.less', './public/style.css', ['./css/*.less']);
        return expect(pckg.style.dependencies).to.be.eql([dir + '/css/common.less', dir + '/css/style.less', dir + '/css/variables.less']);
      });
    });
    return describe('#addModule()', function() {
      it('should add module with absolute path', function() {
        pckg.addModule(dir + '/modules/1.js');
        expect(pckg.modules).to.include.keys('package/modules/1.js');
        return expect(pckg.modules['package/modules/1.js']).to.be.equal(dir + '/modules/1.js');
      });
      it('should add modules with absolute path', function() {
        pckg.addModule(dir + '/modules/*.js<$>');
        return expect(pckg.modules).to.include.keys(['package/modules/1.js', 'package/modules/2.js', 'package/modules/3.js', 'package/modules/4.js', 'package/modules/6.js']);
      });
      it('should add core module', function() {
        pckg.addModule('events');
        return expect(pckg.modules).to.include.keys('events');
      });
      it('should add module from base directory', function() {
        pckg.addModule('./modules/1.js');
        expect(pckg.modules).to.include.keys('modules/1.js');
        return expect(pckg.modules['modules/1.js']).to.be.equal(dir + '/modules/1.js');
      });
      it('should add modules from base directory', function() {
        pckg.addModule('./modules/*.js<$>');
        return expect(pckg.modules).to.include.keys(['modules/1.js', 'modules/2.js', 'modules/3.js', 'modules/4.js', 'modules/6.js']);
      });
      it('should add installed npm module', function() {
        pckg.addModule('module/test.js');
        expect(pckg.modules).to.include.keys('module/test.js');
        return expect(pckg.modules['module/test.js']).to.be.equal(dir + '/node_modules/module/test.js');
      });
      return it('should add installed npm modules', function() {
        pckg.addModule('module/*.js<$>');
        return expect(pckg.modules).to.include.keys(['module', 'module/test.js', 'module/test2.js']);
      });
    });
  });

}).call(this);
