// Generated by CoffeeScript 1.6.3
(function() {
  var Builder, Compiler, Helpers, Info, Module, Package, Q, fs, path, required,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Q = require('q');

  required = require('flatten-required');

  Info = require('module-info');

  Compiler = require('source-compiler');

  Module = require('module');

  path = require('path');

  fs = require('fs');

  Package = require('./Package');

  Helpers = require('../Helpers');

  Builder = (function(_super) {
    __extends(Builder, _super);

    Builder.prototype.pckg = null;

    Builder.prototype.autoModule = ['.json', '.eco'];

    function Builder(pckg) {
      this.pckg = pckg;
      if (!(this.pckg instanceof Package)) {
        throw new Error('Package must be an instance of Package/Package');
      }
    }

    Builder.prototype.check = function() {
      if (!fs.existsSync(this.pckg.getBasePath() + '/package.json')) {
        throw new Error('Package has not got package.json file.');
      }
      return this.pckg.prepare();
    };

    Builder.prototype.build = function() {
      var deferred;
      deferred = Q.defer();
      Q.all([this.buildModules(), this.buildAutorun(), this.buildStyles()]).then(function(data) {
        var result;
        result = '/** Generated by SimQ **/\n/** modules **/\n\n' + data[0];
        if (data[1] !== '') {
          result += '\n\n/** run section **/\n\n' + data[1];
        }
        return deferred.resolve({
          js: result,
          css: data[2]
        });
      }).fail(function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Builder.prototype.buildModules = function() {
      var deferred,
        _this = this;
      this.check();
      deferred = Q.defer();
      this.prepareModules().then(function(modules) {
        var alias, c, name, original, _path, _ref;
        c = [_this.loadMain()];
        for (name in modules) {
          _path = modules[name];
          c.push(_this.compileModule(name, _path));
        }
        _ref = _this.pckg.aliases;
        for (alias in _ref) {
          original = _ref[alias];
          c.push(Q.resolve("'" + alias + "': function(exports, module) { module.exports = window.require('" + original + "'); }"));
        }
        return Q.all(c).then(function(data) {
          var main;
          main = data.shift();
          return deferred.resolve("" + main + "({\n" + data + "\n});");
        }).fail(function(err) {
          return deferred.reject(err);
        });
      }).fail(function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Builder.prototype.buildAutorun = function() {
      var deferred, run, _i, _len, _path, _ref;
      this.check();
      deferred = Q.defer();
      run = [];
      _ref = this.pckg.run;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _path = _ref[_i];
        run.push(this.loadForAutorun(_path));
      }
      Q.all(run).then(function(data) {
        return deferred.resolve(data.join('\n'));
      }).fail(function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Builder.prototype.buildStyles = function() {
      var deferred, options;
      this.check();
      if (this.pckg.style === null) {
        return Q.resolve(null);
      }
      deferred = Q.defer();
      options = {};
      if (this.pckg.style.dependencies !== null) {
        options.dependents = this.pckg.style.dependencies;
      }
      Compiler.compileFile(this.pckg.style["in"], options).then(function(data) {
        return deferred.resolve(data);
      }).fail(function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Builder.prototype.loadForAutorun = function(_path) {
      var deferred;
      deferred = Q.defer();
      if (fs.existsSync(_path)) {
        Compiler.compileFile(_path).then(function(data) {
          return deferred.resolve(data);
        }).fail(function(err) {
          return deferred.reject(err);
        });
      } else {
        deferred.resolve("require('" + _path + "');");
      }
      return deferred.promise;
    };

    Builder.prototype.prepareModules = function() {
      var deferred, paths, _i, _len, _path, _ref,
        _this = this;
      deferred = Q.defer();
      paths = [];
      _ref = this.pckg.modules;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _path = _ref[_i];
        paths.push(_path);
      }
      required.findMany(paths, true, require('../../data.json').supportedCores).then(function(data) {
        var dir, file, info, name, result, _j, _k, _len1, _len2, _ref1, _ref2;
        result = {};
        data.files = data.files.concat(paths);
        data.files = data.files.filter(function(el, pos) {
          return data.files.indexOf(el) === pos;
        });
        _ref1 = data.files;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          file = _ref1[_j];
          if (_this.pckg.getPackageInfo().isFileInModule(file)) {
            result['/' + _this.pckg.getPackageInfo().getModuleName(file, true)] = file;
          } else {
            dir = path.dirname(file);
            if (Module.globalPaths.indexOf(dir) === -1) {
              info = Info.fromFile(file);
              result[info.getModuleName(file)] = file;
            } else {
              name = path.basename(file, path.extname(file));
              result[name] = file;
            }
          }
        }
        _ref2 = data.core;
        for (_path = _k = 0, _len2 = _ref2.length; _k < _len2; _path = ++_k) {
          name = _ref2[_path];
          if (_path !== null) {
            result[name] = _path;
          }
        }
        return deferred.resolve(result);
      }).fail(function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Builder.prototype.compileModule = function(name, _path) {
      var deferred,
        _this = this;
      deferred = Q.defer();
      Compiler.compileFile(_path, {
        precompile: true
      }).then(function(result) {
        var globals, type;
        type = path.extname(_path);
        if (_this.autoModule.indexOf(type) !== -1) {
          result = "module.exports = " + result;
        }
        if (result !== '') {
          result = '\n\n\t/** code **/\n\t' + result.replace(/\n/g, '\n\t') + '\n';
        } else {
          result = '\n';
        }
        globals = '\t' + Helpers.getGlobalsForModule(name).join('\n').replace(/\n/g, '\n\t');
        result = "'" + name + "': function(exports, module) {\n\n\t/** node globals **/\n" + globals + result + "\n}";
        return deferred.resolve(result);
      }).fail(function(err) {
        return deferred.reject(err);
      });
      return deferred.promise;
    };

    Builder.prototype.loadMain = function() {
      var deferred, _path;
      deferred = Q.defer();
      _path = path.resolve(__dirname + '/../_Module.js');
      fs.readFile(_path, {
        encoding: 'utf8'
      }, function(err, data) {
        if (err) {
          return deferred.reject(err);
        } else {
          data = data.replace(/\s+$/, '').replace(/;$/, '');
          return deferred.resolve(data);
        }
      });
      return deferred.promise;
    };

    return Builder;

  })(Package);

  module.exports = Builder;

}).call(this);
