// Generated by CoffeeScript 1.6.3
(function() {
  var Factory, Package;

  Package = require('./Package');

  Factory = (function() {
    function Factory() {}

    Factory.create = function(config) {};

    return Factory;

  })();

  module.exports = Factory;

}).call(this);
