// Generated by CoffeeScript 1.6.3
(function() {
  var Factory, Package;

  Package = require('./Package');

  Factory = (function() {
    function Factory() {}

    Factory.create = function(basePath, config) {
      var m, name, pckg, _i, _j, _len, _len1, _ref, _ref1, _ref2;
      pckg = new Package(basePath);
      pckg.skip = config.skip;
      pckg.base = config.base;
      if (config.application !== null) {
        pckg.setApplication(config.application);
      }
      if (config.style !== null) {
        pckg.setStyle(config.style["in"], config.style.out, config.style.dependencies);
      }
      _ref = config.modules;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        m = _ref[_i];
        pckg.addModule(m);
      }
      _ref1 = config.aliases;
      for (name in _ref1) {
        m = _ref1[name];
        pckg.addAlias(m, name);
      }
      _ref2 = config.run;
      for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
        name = _ref2[_j];
        pckg.addToAutorun(name);
      }
      return pckg;
    };

    return Factory;

  })();

  module.exports = Factory;

}).call(this);
