// Generated by CoffeeScript 1.6.3
(function() {
  var Cache, Compilers, FileStorage, Finder, Loader, Q, fs, http, https, _path;

  Q = require('q');

  _path = require('path');

  fs = require('fs');

  http = require('http');

  https = require('https');

  Cache = require('cache-storage');

  FileStorage = require('cache-storage/Storage/FileStorage');

  Finder = require('fs-finder');

  Compilers = require('./Compilers');

  Loader = (function() {
    Loader.CACHE_NAMESPACE = 'simq.files';

    Loader.prototype.simq = null;

    Loader.prototype.compilers = null;

    Loader.prototype.cache = null;

    function Loader(simq) {
      var cacheDirectory;
      this.simq = simq;
      this.compilers = new Compilers(this.simq);
      cacheDirectory = this.simq.config.load().cache.directory;
      if (cacheDirectory !== null) {
        this.cache = new Cache(new FileStorage(_path.resolve(cacheDirectory)), Loader.CACHE_NAMESPACE);
      }
    }

    Loader.prototype.isCacheAllowed = function(path, packageName) {
      var dependencies, _ref;
      if (packageName == null) {
        packageName = null;
      }
      if (this.cache === null) {
        return false;
      }
      if (path.match(/^https?\:\/\//) !== null) {
        return false;
      }
      if ((_ref = _path.extname(path)) !== '.less' && _ref !== '.scss' && _ref !== '.styl') {
        return true;
      }
      if (packageName === null) {
        return false;
      }
      dependencies = this.simq.config.load().packages[packageName].style.dependencies;
      if (dependencies.length > 0) {
        return dependencies;
      } else {
        return false;
      }
    };

    Loader.prototype.loadFromPath = function(path) {
      var deferred, ext, protocol;
      deferred = Q.defer();
      ext = _path.extname(path).substr(1);
      if (path.match(/^https?\:\/\//) === null) {
        path = _path.resolve(path);
        fs.readFile(path, 'utf-8', function(e, data) {
          if (e) {
            return deferred.reject(new Error(e));
          } else {
            return deferred.resolve({
              path: path,
              ext: ext,
              content: data
            });
          }
        });
      } else {
        protocol = path.match(/^https/) === null ? http : https;
        protocol.get(path, function(res) {
          var data;
          data = '';
          res.setEncoding('utf-8');
          res.on('data', function(chunk) {
            return data += chunk;
          });
          return res.on('end', function() {
            return deferred.resolve({
              path: path,
              ext: ext,
              content: data
            });
          });
        }).on('error', function(e) {
          return deferred.reject(new Error(e));
        });
      }
      return deferred.promise;
    };

    Loader.prototype.finalizeFile = function(path, content, packageName) {
      var deferred,
        _this = this;
      deferred = Q.defer();
      this.compilers.prepare(path, content).then(function(content) {
        var dependencies, files, _i, _len;
        if ((dependencies = _this.isCacheAllowed(path, packageName)) !== false && _this.cache.load(path) === null) {
          files = [path];
          if (dependencies !== true) {
            for (_i = 0, _len = dependencies.length; _i < _len; _i++) {
              path = dependencies[_i];
              files = files.concat(Finder.findFiles(path));
            }
          }
          _this.cache.save(path, content, {
            files: files
          });
        }
        return deferred.resolve(content);
      }, function(e) {
        return deferred.reject(e);
      });
      return deferred.promise;
    };

    Loader.prototype.loadFile = function(path, packageName) {
      var data, deferred,
        _this = this;
      if (packageName == null) {
        packageName = null;
      }
      if (path.match(/^https?\:\/\//) === null) {
        path = _path.resolve(path);
      }
      if (_path.basename(path, _path.extname(path)).substr(0, 1) === '.' || path.substring(path.length - 1) === '~') {
        return Q.resolve(null);
      }
      if (this.isCacheAllowed(path, packageName) !== false && (data = this.cache.load(path)) !== null) {
        return Q.resolve(data);
      }
      deferred = Q.defer();
      this.loadFromPath(path).then(function(data) {
        return _this.finalizeFile(data.path, data.content, packageName).then(function(content) {
          return deferred.resolve(content);
        });
      });
      return deferred.promise;
    };

    Loader.prototype.prepareModule = function(path) {
      var deferred, ext;
      deferred = Q.defer();
      path = _path.resolve(path);
      ext = _path.extname(path).substr(1);
      if (!this.compilers.hasCompiler(ext)) {
        deferred.reject(new Error('File type ' + ext + ' is not supported'));
      } else {
        this.loadFile(path).then(function(content) {
          if (content === null) {
            return deferred.resolve(null);
          } else {
            return deferred.resolve({
              path: path,
              content: content
            });
          }
        }, function(e) {
          return deferred.reject(e);
        });
      }
      return deferred.promise;
    };

    Loader.prototype.loadModule = function(path, base) {
      var deferred,
        _this = this;
      if (base == null) {
        base = null;
      }
      deferred = Q.defer();
      this.prepareModule(path).then(function(data) {
        var name;
        if (data === null) {
          return deferred.resolve(null);
        } else {
          name = _this.simq.getModuleName(data.path);
          if (base !== null) {
            name = name.replace(new RegExp('^' + base + '/'), '');
          }
          return _this.compilers.compile(data.path, data.content).then(function(content) {
            return deferred.resolve('\'' + name + '\': function(exports, _r, module) {\nvar require = function(name) {return _r(name, \'' + name + '\');};\n' + content + '\n}');
          });
        }
      });
      return deferred.promise;
    };

    return Loader;

  })();

  module.exports = Loader;

}).call(this);
